name: deploy via ssh

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
env:
  jobid: ${{ github.run_id }}
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.DUSER }}
        key: ${{ secrets.SSH_PK }}
        script: |
          echo ${{ env.jobid }};
          cd neiro-back;
          git checkout dev;
          git pull;
          prospector --profile .prospector.yaml
          python manage.py test --keepdb
          docker build -f Dockerfile -t neiro-back-dev:${{ env.jobid }} .;
          docker run  -d -p 8001:8000 --name neiro-back-dev neiro-back-dev:${{ env.jobid }};
          docker system prune --all --force;
